services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/conversafe
      - AI_URL=${AI_URL:-http://localhost:8000}
      - JWT_SECRET=supersecreto
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge 