services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL:-http://localhost:3000}
    container_name: frontend
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
      - VITE_SOCKET_URL=${VITE_SOCKET_URL:-http://localhost:3000}
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 