services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 