# -*- coding: utf-8 -*-
"""payload

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GbFr08qfz4WpsJNLDmjLMAfCDJr4bLNU
"""

{
    "mensajes": [
        {
            "usuario": "Alex",
            "texto": "Necesitamos resolver este bug urgente, nos esta dando muchos problemas y no hay nadie arreglandolo.",
            "marca_de_tiempo": "2024-07-03T10:00:00Z"
        },
        {
            "usuario": "Maria",
            "texto": "Estoy trabajando en eso ahora mismo.",
            "marca_de_tiempo": "2024-07-03T10:01:00Z"
        }
    ]
}